// AI Pipeline is the advanced trainer shortlist page with AI-powered email generation
// This is actually Shortlist1 with Gemini AI integration for automatic email generation
import Shortlist1 from './Shortlist1'

export default function AIPipeline() {
  return <Shortlist1 />
}

/*
// Old basic stats version - replaced with Shortlist1 which has:
// - 🤖 AI Email Generation (Gemini AI generates next email automatically)
// - 📱 Multi-channel sending (Email, WhatsApp, Teams DM, Teams Channel)
// - 📊 Bulk send status (tracks success across all channels)
// - 🎯 Advanced trainer management with AI

// Legacy code below (kept for reference):
import { useEffect, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { Zap, TrendingUp, CheckCircle2, AlertCircle, Users, Mail, Flame } from 'lucide-react'
import api from '../utils/api'

function AIPipelineOld() {
  const navigate = useNavigate()
  const [automationStats, setAutomationStats] = useState({
    total_requirements: 0,
    shortlists_auto_generated: 0,
    mails_auto_sent: 0,
    trainers_shortlisted: 0,
  })
  const [recentAutomations, setRecentAutomations] = useState([])
  const [loading, setLoading] = useState(true)

  useEffect(() => {
    loadAutomationStats()
  }, [])

  const loadAutomationStats = async () => {
    try {
      setLoading(true)
      
      // Get all requirements to calculate stats
      const reqRes = await api.get('/requirements')
      const requirements = reqRes.data?.requirements || []
      
      // Get all shortlists
      const shortlistRes = await api.get('/shortlists')
      const shortlists = shortlistRes.data?.shortlists || []

      // Calculate stats
      const autoGenerated = shortlists.filter(s => s.auto_created).length
      const totalTrainers = shortlists.reduce((sum, s) => sum + (s.top_trainers?.length || 0), 0)

      // Get recent email logs for auto-sent mails
      const emailRes = await api.get('/emails?limit=100')
      const emails = emailRes.data?.emails || []
      const autoSentMails = emails.filter(e => e.source === 'auto_immediate_search' || e.mail_type === 'mail1').length

      setAutomationStats({
        total_requirements: requirements.length,
        shortlists_auto_generated: autoGenerated,
        mails_auto_sent: autoSentMails,
        trainers_shortlisted: totalTrainers,
      })

      // Get recent auto-generated shortlists
      const recent = shortlists
        .filter(s => s.auto_created)
        .sort((a, b) => new Date(b.generated_date) - new Date(a.generated_date))
        .slice(0, 5)
        .map(s => ({
          requirement_id: s.requirement_id,
          domain: s.domain || s.technology_needed,
          trainer_count: s.top_trainers?.length || 0,
          generated_date: s.generated_date,
          status: 'Auto-Generated ✅',
        }))

      setRecentAutomations(recent)
    } catch (error) {
      console.error('Error loading automation stats:', error)
    } finally {
      setLoading(false)
    }
  }

  if (loading) {
    return (
      <div className="flex min-h-screen items-center justify-center">
        <div className="text-slate-500">Loading automation stats...</div>
      </div>
    )
  }

  return (
    <div className="space-y-6">
      {/* Header */}
      <div>
        <div className="flex items-center gap-3">
          <div className="rounded-lg bg-gradient-to-br from-violet-500 to-purple-600 p-2">
            <Zap className="h-6 w-6 text-white" />
          </div>
          <div>
            <h1 className="text-3xl font-bold text-slate-900">AI Pipeline Automation</h1>
            <p className="text-sm text-slate-500 mt-1">Automatic trainer matching and outreach</p>
          </div>
        </div>
      </div>

      {/* Stats Grid */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
        {/* Total Requirements */}
        <div className="bg-white rounded-2xl border border-slate-200 p-6 hover:border-slate-300 transition-all">
          <div className="flex items-center justify-between mb-4">
            <div className="text-slate-500 text-sm font-semibold">Total Requirements</div>
            <AlertCircle className="w-5 h-5 text-orange-500" />
          </div>
          <div className="text-3xl font-bold text-slate-900">{automationStats.total_requirements}</div>
          <p className="text-xs text-slate-400 mt-2">Awaiting processing</p>
        </div>

        {/* Auto-Generated Shortlists */}
        <div className="bg-white rounded-2xl border border-slate-200 p-6 hover:border-slate-300 transition-all">
          <div className="flex items-center justify-between mb-4">
            <div className="text-slate-500 text-sm font-semibold">Shortlists Generated</div>
            <CheckCircle2 className="w-5 h-5 text-emerald-500" />
          </div>
          <div className="text-3xl font-bold text-slate-900">{automationStats.shortlists_auto_generated}</div>
          <p className="text-xs text-slate-400 mt-2">Automatically created</p>
        </div>

        {/* Trainers Shortlisted */}
        <div className="bg-white rounded-2xl border border-slate-200 p-6 hover:border-slate-300 transition-all">
          <div className="flex items-center justify-between mb-4">
            <div className="text-slate-500 text-sm font-semibold">Trainers Matched</div>
            <Users className="w-5 h-5 text-blue-500" />
          </div>
          <div className="text-3xl font-bold text-slate-900">{automationStats.trainers_shortlisted}</div>
          <p className="text-xs text-slate-400 mt-2">Ready for outreach</p>
        </div>

        {/* Auto-Sent Mails */}
        <div className="bg-white rounded-2xl border border-slate-200 p-6 hover:border-slate-300 transition-all">
          <div className="flex items-center justify-between mb-4">
            <div className="text-slate-500 text-sm font-semibold">Auto-Sent Emails</div>
            <Mail className="w-5 h-5 text-violet-500" />
          </div>
          <div className="text-3xl font-bold text-slate-900">{automationStats.mails_auto_sent}</div>
          <p className="text-xs text-slate-400 mt-2">Mail 1 outreach</p>
        </div>
      </div>

      {/* How It Works */}
      <div className="bg-white rounded-2xl border border-slate-200 p-6">
        <div className="flex items-center gap-2 mb-4">
          <Flame className="w-5 h-5 text-orange-500" />
          <h2 className="text-lg font-bold text-slate-900">How AI Pipeline Works</h2>
        </div>
        <div className="space-y-3">
          <div className="flex gap-4 items-start">
            <div className="flex-shrink-0 w-8 h-8 rounded-full bg-violet-100 flex items-center justify-center text-violet-700 font-bold text-sm">1</div>
            <div>
              <p className="font-semibold text-slate-900">Client Response Detection</p>
              <p className="text-sm text-slate-600">When client says "will send details later", system detects it automatically</p>
            </div>
          </div>
          <div className="flex gap-4 items-start">
            <div className="flex-shrink-0 w-8 h-8 rounded-full bg-violet-100 flex items-center justify-center text-violet-700 font-bold text-sm">2</div>
            <div>
              <p className="font-semibold text-slate-900">Auto-Fill Training Details</p>
              <p className="text-sm text-slate-600">Duration: 5 days, Mode: Online, Participants: 10, Level: Intermediate</p>
            </div>
          </div>
          <div className="flex gap-4 items-start">
            <div className="flex-shrink-0 w-8 h-8 rounded-full bg-violet-100 flex items-center justify-center text-violet-700 font-bold text-sm">3</div>
            <div>
              <p className="font-semibold text-slate-900">Shortlist Generation</p>
              <p className="text-sm text-slate-600">System matches and selects top trainers from database</p>
            </div>
          </div>
          <div className="flex gap-4 items-start">
            <div className="flex-shrink-0 w-8 h-8 rounded-full bg-violet-100 flex items-center justify-center text-violet-700 font-bold text-sm">4</div>
            <div>
              <p className="font-semibold text-slate-900">Automatic Mail 1 Outreach</p>
              <p className="text-sm text-slate-600">All trainers receive initial contact email automatically (no manual toggle needed)</p>
            </div>
          </div>
        </div>
      </div>

      {/* Recent Automations */}
      <div className="bg-white rounded-2xl border border-slate-200 p-6">
        <div className="flex items-center gap-2 mb-4">
          <TrendingUp className="w-5 h-5 text-blue-500" />
          <h2 className="text-lg font-bold text-slate-900">Recent Auto-Generated Shortlists</h2>
        </div>
        
        {recentAutomations.length === 0 ? (
          <div className="text-center py-8 text-slate-400">
            No auto-generated shortlists yet
          </div>
        ) : (
          <div className="space-y-3">
            {recentAutomations.map(automation => (
              <div key={automation.requirement_id} className="flex items-center justify-between p-4 bg-slate-50 rounded-xl border border-slate-100 hover:bg-slate-100 transition-all cursor-pointer"
                onClick={() => navigate('/shortlist')}>
                <div className="flex-1">
                  <div className="flex items-center gap-3">
                    <div className="w-10 h-10 rounded-lg bg-blue-100 flex items-center justify-center flex-shrink-0">
                      <CheckCircle2 className="w-5 h-5 text-blue-600" />
                    </div>
                    <div className="min-w-0">
                      <p className="font-semibold text-slate-900">{automation.domain}</p>
                      <p className="text-xs text-slate-500">{automation.requirement_id}</p>
                    </div>
                  </div>
                </div>
                <div className="flex items-center gap-6 flex-shrink-0">
                  <div className="text-right">
                    <p className="text-sm font-bold text-slate-900">{automation.trainer_count} Trainers</p>
                    <p className="text-xs text-slate-500">
                      {automation.generated_date ? new Date(automation.generated_date).toLocaleDateString('en-IN', { month: 'short', day: '2-digit', year: '2-digit' }) : 'N/A'}
                    </p>
                  </div>
                  <div className="text-right">
                    <span className="inline-flex items-center gap-1.5 px-3 py-1 rounded-lg bg-emerald-50 text-emerald-700 text-xs font-semibold">
                      <CheckCircle2 className="w-3.5 h-3.5" />
                      Auto-Generated
                    </span>
                  </div>
                </div>
              </div>
            ))}
          </div>
        )}
      </div>

}
*/
